import { GoogleAnalytics } from '@next/third-parties/google';

// Components
import { Letters } from "@/components/Letters";
import { SiteFrame } from "@/components/SiteFrame";
import { Footer } from "@/components/Footer";
import { SiteMasthead } from "@/components/SiteMasthead";
import { ThemeBackground } from "@/components/ThemeBackground";
import { Main } from "@/components/Main";

// Context
import { Providers } from "./providers";

// Utils
import { classes } from "@/utils";

// Styles
import "./globals.css";
import * as Fonts from './fonts'

export const metadata = {
  title: "Andrew Alford Creative",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const fontData = Object.keys(Fonts).map((font) => Fonts[font].variable);

  return (
    <html lang="en">
      <body className={classes(fontData.join(" "), "antialiased")}>
        <Providers>
          <SiteFrame className="min-h-screen">
            <ThemeBackground className="fixed inset-0" />
            <Letters className="pointer-events-auto" />
            <SiteMasthead className="sticky top-0" />
            <Main className="grow">{children}</Main>
            <Footer className="fixed inset-0 top-auto" />
          </SiteFrame>
        </Providers>
      </body>
      <GoogleAnalytics gaId="G-LDZ8DYQ8P0" />
    </html>
  );
}
