// Components
import { Links } from "@/components/Links";
import { Letters } from "./_components/Letters";
import { Content } from "./_components/Content";
import { Footer } from "./_components/Footer";

// Utils
import { classes, shuffle } from "@/utils";

// Styles
import "./globals.css";
import * as Fonts from './fonts'

// Consts
const PAGES = [
  {
    name: "Articles",
    href: "/articles",
  },
  {
    name: "Selected Projects",
    href: "/selected-projects",
  },
  {
    name: "Contact",
    href: "/contact",
  },
];

export const metadata = {
  title: "Andrew Alford Creative",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const fontData = Object.keys(Fonts).map((font) => Fonts[font].variable);
  const backgroundColor = shuffle(["#ff000e", "#f9ef07", "#1418ea"])[0];
  console.log("backgroundColor", backgroundColor);
  
  return (
    <html lang="en">
      <body
        className={classes(
          fontData.join(" "),
          "antialiased bg-light text-dark dark:bg-dark dark:text-light"
        )}
      >
        {/* <div className="bg-[url(/webb-2.jpg)] fixed inset-0 z-0 bg-cover bg-center" /> */}
        <div className="fixed inset-0 z-1 bg-cover bg-center" style={{ backgroundColor }} />
        <div
          className={classes(
            "relative flex z-3 align-top flex-col min-h-screen gap-8"
          )}
        >
          <h1
            className={classes(
              "flex flex-col uppercase -translate-x-[0.02em] relative z-[10]",
              "text-outline-[currentColor]",
              "text-[#0c1943]"
              // "mix-blend-overlay"
            )}
          >
            <div className="pointer-events-none py-[1vw] translate-y-[0.042em] text-[9.26vw] leading-[0.8] text-center">
              <span className="font-champion-bantamweight">Andrew</span>
              <span className="font-champion-welterweight">Alford</span>
              <span className="font-champion-heviweight">Creative</span>
            </div>
            <Links
              classes={[
                "underline underline-offset-[0.1em] decoration-[0.14em]",
                "underline underline-offset-[0.1em] decoration-[0.14em] [word-spacing:-0.15em]",
                "underline underline-offset-[0.1em] decoration-[0.14em]",
              ]}
              className="flex translate-y-[0.042em] text-[4.75vw] leading-[0.8] justify-center"
              decorated={false}
              fonts={[
                "font-champion-liteweight",
                "font-champion-heviweight",
                "font-champion-middleweight",
              ]}
              links={PAGES}
              spacing="gap-3"
            />
          </h1>
          <div className="flex grow items-start">
            <Letters className="z-2" />
            {/* <Header className="z-3" /> */}
            <Content className="pointer-events-auto relative z-3">
              {children}
            </Content>
          </div>
          <Footer className="z-2" />
        </div>
      </body>
    </html>
  );
}
