// Components
import { Link } from "@/components/Link";
import { Letters } from "@/components/Letters";
import { Content } from "@/components/Content";
// import { Footer } from "@/components/Footer";
import { SiteMasthead } from "@/components/SiteMasthead";
import { ThemeBackground } from "@/components/ThemeBackground";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";

// Context
import { DraggingProvider } from "@/context/DraggingContext";
import { ThemeProvider } from "@/context/ThemeContext";

// Utils
import { classes } from "@/utils";

// Assets
import Logo from "@/assets/svg/logo.svg";

// Styles
import "./globals.css";
import * as Fonts from './fonts'

export const metadata = {
  title: "Andrew Alford Creative",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const fontData = Object.keys(Fonts).map((font) => Fonts[font].variable);

  return (
    <html lang="en">
      <body className={classes(fontData.join(" "), "antialiased")}>
        <Link className="fixed bottom-4 left-4 z-50 text-foreground mix-blend-luminosity" href="/">
          <Logo className="w-[70px]" />
        </Link>
        <ThemeProvider>
          <DraggingProvider>
            <Content className="min-h-screen relative z-4">
              <ThemeBackground className="fixed inset-0 z-[-1]" />
              <Letters className="pointer-events-auto z-3" />
              <SiteMasthead className="sticky z-4" />
              {/* <Footer className="sticky z-4" /> */}
              <main className="grow">{children}</main>
            </Content>
          </DraggingProvider>
          <ThemeSwitcher />
        </ThemeProvider>
      </body>
    </html>
  );
}
