import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

// Components
import { Letters } from "./_components/Letters";
import { Header } from "./_components/Header";
import { Content } from "./_components/Content";
import { Footer } from "./_components/Footer";

// Utils
import { classes } from "@/utils";

// Styles
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// Local font definitions
const ringsideRegular = localFont({
  src: [
    {
      path: "../assets/fonts/RingsideRegular-Book.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/RingsideRegular-BookItalic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../assets/fonts/RingsideRegular-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/fonts/RingsideRegular-SemiboldItalic.woff2",
      weight: "600",
      style: "italic",
    },
  ],
  variable: "--font-ringside-regular",
  display: "swap",
});

const crimsonCurse = localFont({
  src: "../assets/fonts/Crimson-Curse.woff2",
  variable: "--font-crimson-curse",
  display: "swap",
});

const decimal = localFont({
  src: "../assets/fonts/Decimal-Book-Pro.woff2",
  variable: "--font-decimal",
  display: "swap",
});

export const metadata = {
  title: "Andrew Alford Creative",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ringsideRegular.variable} ${crimsonCurse.variable} ${decimal.variable} antialiased bg-light text-dark dark:bg-dark dark:text-light`}
      >
        <div className="bg-fixed bg-[radial-gradient(#999_1px,transparent_2px)] bg-size-[20px_20px] fixed -inset-8 -rotate-[1.5deg] z-1" />
        <div className={classes("relative flex z-3 align-top flex-col min-h-screen gap-8", /*"pointer-events-none"*/)}>
          <div className="flex grow items-start">
            <Letters className="z-2" />
            <Header className="z-3" />
            <Content className="pointer-events-auto relative z-3">{children}</Content>
          </div>
          <Footer className="z-2" />
        </div>
      </body>
    </html>
  );
}
