export const NAMES: string[] = [
  "Divine",
  "Mr. David",
  "Bonnie",
  "Mink",
  "Cookie Divine",
  "The Infant of Prague",
  "Babs Johnson",
  "Edie",
  "Crackers",
  "Cotton",
  "Connie and Raymond Marble",
  "Dawn Davenport",
  "Aunt Ida",
  "Taffy Davenport",
  "Donna Dasher",
  "Vikki",
  "Princess Coo Coo",
  "Queen Carlotta",
  "Mole McHenry",
  "Peggy Gravel",
  "Francine Fishpaw",
  "Todd Tomorrow",
  "Sandra Sullivan",
  "Cuddles Kovinsky",
  "Tracy Turnblad",
  "Edna Turnblad",
  "Wilbur Turnblad",
  "Velma Von Tussle",
  "Amber Von Tussle",
  "Seaweed J. Stubbs",
  "Little Inez",
  "Motormouth Maybelle",
  "Corny Collins",
  "Cry-Baby Walker",
  "Wanda Woodward",
  "Corinne",
  "Allison Vernon-Walker",
  "Horace",
  "Beverly Sutphin",
  "Eugene Sutphin",
  "Chip Sutphin",
  "Misty Sutphin",
  "Detective Pike",
  "Detective Gracey",
  "Scotty",
  "Birdie",
  "Carl",
  "Dottie Hinkle",
  "Rosemary Ackerman",
  "Ralph Sterner",
  "Betty Sterner",
  "Marvin Pickles",
  "Howell Hawkins",
  "Father Boyce",
  "Sloppy",
  "Juror #8",
];

export const TITLES: string[] = [
  "Owner, Principal",
  "Founder, CEO",
  "President, CEO",
  "CEO",
  "President",
  "Founder",
  "Owner",
  "Principal",
];

export const MESSAGES: string[] = [
  "“I didn’t claw my way out of nothing, build this company, and bury two husbands just to let you waltz in here with a smile and a signature and take it from me. You want my name on that contract? Pry the pen from my cold, perfectly manicured hand.”",
  "“You keep calling this a family, but families don’t stab each other in the back over breakfast. They don’t hide wills in desk drawers and lovers in guest houses. This isn’t a family—it’s a battlefield with better china.”",
  "“Don’t you dare look at me like I’m the villain. I protected you. I lied for you. I burned my whole life down for you. And now you’re shocked to find smoke on your clothes?”",
  "“This house was built on my father’s money and my mother’s tears. Every brick has a secret in it. If you think you can move in here and pretend none of that happened, you’re going to find out exactly how loud the walls can scream.”",
  "“You talk about love like it’s poetry. I talk about love like it’s war. Love costs. Love bleeds. And if you’re not willing to lose everything for it, then don’t you dare say you love me.”",
  "“I didn’t steal your husband. He walked out the door all by himself. The only thing I gave him was a reason to stop pretending he was happy.”",
  "“You want the truth? Fine. The baby isn’t yours, the company isn’t safe, and the only reason I stayed was to make sure you never forgot what you did to me. Sleep tight.”",
  "“I’ve been underestimated my entire life—too soft, too quiet, too polite. Funny thing about quiet people: we hear everything. And now I know exactly where to aim.”",
  "“You think money makes you powerful. Money just makes you loud. Power is knowing everyone’s secrets and deciding which one to whisper at the right moment.”",
  "“I forgave you for the affair. I forgave you for the lies. But showing up here and acting like we can go back to normal? That’s not love. That’s amnesia, and I refuse to forget what you did.”",
  "“I buried my past, changed my name, and started over. Then you showed up with that smile like nothing ever happened. Some ghosts don’t rattle chains—they wear cologne and call you sweetheart.”",
  "“You keep saying ‘it’s just business.’ Funny. Business doesn’t usually involve my sister’s tears, my father’s grave, and you sleeping in my bed.”",
];

type Film = {
  characters: string[];
  quotes: string[];
  title: string;
};

export const FILMS: Film[] = [
  {
    title: "This Is Spinal Tap",
    characters: [
      "Nigel Tufnel",
      "David St. Hubbins",
      "Derek Smalls",
      "Marty DiBergi",
      "Jeanine Pettibone",
      "Ian Faith",
      "Viv Savage",
      "Mick Shrimpton",
      "Joe “Mama” Besser",
      "Ronnie Pudding",
      "Artie Fufkin",
      "Bobbi Flekman",
      "Tommy Pischedda",
    ],
    quotes: [
      "These go to eleven.",
      "It’s such a fine line between stupid and clever.",
      "Hello, Cleveland!",
      "We’re very lucky in the band in that we have two visionaries.",
      "Turn it up to eleven.",
    ],
  },
  {
    title: "Waiting for Guffman",
    characters: [
      "Corky St. Clair",
      "Sheila Albertson",
      "Ron Albertson",
      "Libby Mae Brown",
      "Clifford Wooley",
      "Johnny Savage",
      "Lloyd Miller",
      "Dr. Allan Pearl",
      "Naomi Steinberg",
      "Red Savage",
      "Harold Steinberg",
    ],
    quotes: [
      "I hate you and I hate your ass face!",
      "This is my life, right here.",
      "We’re doing a musical about Blaine.",
      "I’ve been in 42 productions.",
      "Guffman’s coming.",
    ],
  },
  {
    title: "Best in Show",
    characters: [
      "Gerry Fleck",
      "Cookie Fleck",
      "Meg Swan",
      "Hamilton Swan",
      "Harlan Pepper",
      "Sherri Ann Cabot",
      "Christy Cummings",
      "Stefan Vanderhoof",
      "Scott Donlan",
      "Trevor Beckwith",
      "Leslie Ward Cabot",
      "Jim Pimento",
    ],
    quotes: [
      "Leslie and I have an amazing relationship and it’s very physical, he still pushes all my buttons. People say “oh but he’s so much older than you’ and you know what, I’m the one having to push him away. We have so much in common, we both love soup and snow peas, we love the outdoors, and talking and not talking. We could not talk or talk forever and still find things to not talk about.",
      "I used to be able to name every nut that there was. And it used to drive my mother crazy, because she used to say, “Harlan Pepper, if you don’t stop naming nuts,” and the joke was that we lived in Pine Nut, and I think that’s what put it in my mind at that point. So she would hear me in the other room, and she’d just start yelling. I’d say, “Peanut. Hazelnut. Cashew nut. Macadamia nut.” That was the one that would send her into going crazy. She’d say, “Would you stop naming nuts!” And Hubert used to be able to make the sound, he couldn’t talk, but he’d go “rrrawr rrawr” and that sounded like Macadamia nut. Pine nut, which is a nut, but it’s also the name of a town. Pistachio nut. Red pistachio nut. Natural, all natural white pistachio nut.",
      "Not that I didn’t have quite the reputation myself. I was known by, you know, “some”, to be quite the Casanova.",
      "I was born with two left feet.",
      "We met at Starbucks. Not at the same Starbucks but we saw each other at different Starbucks across the street from each other.",
      "I remember what I was drinking when I met you. It was a grande espresso. That’s right. And you thought that was really sexy.",
      "Doctor, question that’s always bothered me and a lot of people: Mayflower, combined with Philadelphia - a no-brainer, right? Cause this is where the Mayflower landed. Not so. It turns out Columbus actually set foot somewhere down in the West Indies. Little known fact.",
      "You know something, what you don’t understand is... what do they say?... one picture is worth a thousand words. I only went through 125 or 130 words describing that. If I wanted to go on, I could go through 800 words more.",
      "Well, it’s breathing now, but it’ll be hot down there. I could go with the lambswool, but then again, you’ll see a lot of khaki down there and this merlot looks good with the gray.",
      "We got to open this, this, these offices, and publish this magazine here, ‘American Bitch’. The dog magazine for women and their dogs. Umm, it’s a focus on the issues of the lesbian pure bred dog owner.",
      "When I started here all there was was lampshade warehouses and leather bars, the serious leather bars where you wouldn’t get in unless you had a rubber ball stuffed in your mouth, the wine list was tattooed on the bar tender’s face. That kind of place. I remember one guy had a bicycle reflector sewn onto one nipple.",
    ],
  },
];
